<template>
  <div class="coColorScheme">
    <h1 class="u4">Color scheme:</h1>
    <div>
      <p
        class="u2 --bold scheme"
        v-for="colorScheme in colorSchemes"
        :key="colorScheme.styleClass"
        :class="colorScheme.styleClass"
      >
        {{colorScheme.label}}
      </p>
    </div>
  </div>
</template>

<script lang="ts">
  import Vue from 'vue';
  import { Component } from 'vue-property-decorator';

  @Component
  export default class ColorScheme extends Vue {
    public colorSchemes: Array<{ styleClass: string, label: string }> = [
      {
        styleClass: 'isAvailable',
        label: 'Available',
      },
      {
        styleClass: 'isAutoGenerated',
        label: 'Auto generated',
      },
      {
        styleClass: 'isBreak',
        label: 'Break',
      },
      {
        styleClass: 'isReserved',
        label: 'Reserved',
      },
    ];
  }
</script>

<style lang="scss" scoped>
  .coColorScheme {
    padding: 0 percentage(4 / 24);

    .scheme {
      padding: 5px 10px;

      &.isAvailable {
        background-color: $available;
      }

      &.isAutoGenerated {
        background-color: $generated;
      }

      &.isBreak {
        background-color: $break;
      }

      &.isReserved {
        background-color: $reserved;
      }
    }
  }
</style>
